name: "Build"

on:
  pull_request:
    branches:
      - dev

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: "Build and run backend"
        working-directory: ./server
        run: docker-compose build && docker-compose up -d

      - name: "Stop backend"
        working-directory: ./server
        run: docker-compose stop && docker-compose down

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Build android app"
        working-directory: ./app/android
        run: ./gradlw assembleRelease
