name: "Build"

on:
  push:
    branches:
      - "*"
      - "*/"
      - "**"
      - "!master"
      - "!dev"

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: "Create env file"
        run: |
          cd server
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env

      - name: "Build and run backend"
        run: |
          cd server
          docker-compose build && docker-compose up -d

      - name: "Stop backend"
        working-directory: ./server
        run: |
          docker-compose stop && docker-compose down

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install npm dependencies
        run: |
          cd app
          npm install
      - name: Create env file
        run: |
          cd app
          touch .env
          echo API_URL=${{ secrets.API_URL }} >> .env
      - name: Build Android Release
        run: cd app/android && ./gradlew assembleDebug

      - name: "Upload APK"
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/android/app/build/outputs/apk/debug/app-debug.apk
